import pyttsx3
import databas as d
import time
def printf(str):
    engine = pyttsx3.init()
    engine.say(str)
    print(str)
    engine.runAndWait()
def sleep(x):
    time.sleep(x)
def timer_10():
    for x in range(10):
        if(x==5):
            printf("walk")
        printf(str(x+1))
        sleep(1)
def timer_30():
    for x in range(30):
        if(x==15):
            printf("Half Time")
        printf(str(x+1))     
        sleep(1)
def assign():
    height=d.fetchheight()
    weight=d.fetchweight()
    print(height)
    print(weight)

    bmi = weight/((height/100)**2)
    x=bmi
    print(x)

    if(x<18.5):
        printf("Underweight")
        workout_1()
    elif (x>=18.5 and x<=24.9):
        printf(" Normal")
        workout_2()        
    
    elif (x>=25.0 and x<=29.9):
        printf(" Overweight")
        workout_3()
        
    
    elif (x>=30.0 and x<=34.9):
        printf("Obese")
        workout_4()
        
    elif(x>34.9):
        printf("Extremely obese") 
        workout_5()
    else:
        printf("We got only 1 to 5 workout plans")
    
def workout_1():
    printf(" Generating a special workout plan ")
    sleep(2)
    printf("Its a special workout plan for under weight. \n lets begin")
    sleep(1)
    printf("JUMPING JACKS")
    sleep(1)
    printf("Do for 30 seconds")
    sleep(1)  
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PUSH ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PULL ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT SQUATS")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("UP NEXT LUNGES")
    sleep(1)
    printf(" Do it for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("CRUNCHES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PULL ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT SQUATS")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("UP NEXT LUNGES")
    sleep(1)
    printf(" Do it for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("CRUNCHES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("Voila That's it for today")
    sleep(1)
    printf("Stay healthy Cheers")

def workout_2():
   
    printf("You're good,but as you know never settle for good be better. Let's work on strengthening")
    printf("Its a special workout plan for Normal. lets begin")
    sleep(1)
    printf("JUMPING JACKS")
    printf("Do for 30 seconds")
    sleep(1)
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PUSH ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PULL ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT SQUATS")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
   
    sleep(1)
    printf("UP NEXT LUNGES")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("JUMPING LUNGES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("BURPEE")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("CRUNCHES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PUSH ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PULL ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT SQUATS")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("UP NEXT LUNGES")
    sleep(1)
    printf(" Do it for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("CRUNCHES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PULL ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT SQUATS")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("UP NEXT LUNGES")
    sleep(1)
    printf(" Do it for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("CRUNCHES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("Voila That's it for today")
    sleep(1)
    printf("Stay healthy Cheers")

def workout_3():
    printf(" Warning You are losing shape, Do something today that your future self will thank you for")
    sleep(2)
    printf("Its a special workout plan for Overweight. lets begin")
    sleep(2)
    printf("JUMPING JACKS")
    sleep(1)
    printf("Do for 30 seconds")
    sleep(1)
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PUSH ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PULL ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT SQUATS")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PUSH ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PULL ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT SQUATS")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PUSH ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PULL ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT SQUATS")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("UP NEXT LUNGES")
    sleep(1)
    printf(" Do it for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("CRUNCHES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PULL ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT SQUATS")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("UP NEXT LUNGES")
    sleep(1)
    printf(" Do it for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("CRUNCHES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
   
    sleep(1)
    printf("UP NEXT LUNGES")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("JUMPING LUNGES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("BURPEE")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("CRUNCHES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()   
    sleep(1)
    printf("UP NEXT LUNGES")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("JUMPING LUNGES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PUSH ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PULL ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT SQUATS")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("UP NEXT LUNGES")
    sleep(1)
    printf(" Do it for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("CRUNCHES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PULL ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT SQUATS")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("UP NEXT LUNGES")
    sleep(1)
    printf(" Do it for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("CRUNCHES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("BURPEE")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("CRUNCHES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("PLANK")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("PUSHups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("Voila That's it for today")
    sleep(1)
    printf("Stay healthy Cheers")

def workout_4():
    printf(" Wake up dear friend Still not late, TRAIN INSANE OR REMAIN THE SAME")
    printf("Its a special workout plan for Obese. lets begin")
    sleep(1)
    printf("JUMPING JACKS")
    printf("Do for 30 seconds")
    sleep(1)
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PUSH ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PULL ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT SQUATS")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
   
    sleep(1)
    printf("UP NEXT LUNGES")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("JUMPING LUNGES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("BURPEE")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("CRUNCHES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("PLANK")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("PUSHups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PUSH ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PULL ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT SQUATS")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
   
    sleep(1)
    printf("UP NEXT LUNGES")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("JUMPING LUNGES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("BURPEE")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("CRUNCHES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("PLANK")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("PUSHups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("Voila That's it for today")
    sleep(1)
    printf("Stay healthy Cheers")
def workout_5():

    printf(" Dear friend, Everything is possible")
    sleep(1)
    printf("Losing weight is Hard, Being fat is HARD, Choose your hard")
    sleep(1)
    printf("Its a special workout plan for Extremely . lets begin")
    sleep(1)
    printf("JUMPING JACKS")
    printf("Do for 30 seconds")
    sleep(1)
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
     printf("NEXT PUSH ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PULL ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT SQUATS")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PUSH ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PULL ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT SQUATS")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
   
    sleep(1)
    printf("UP NEXT LUNGES")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("JUMPING LUNGES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("BURPEE")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("CRUNCHES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()   
    sleep(1)
    printf("UP NEXT LUNGES")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("JUMPING LUNGES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("BURPEE")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("CRUNCHES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("PLANK")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("PUSHups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PUSH ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PULL ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT SQUATS")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PUSH ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PULL ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT SQUATS")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
   
    sleep(1)
    printf("UP NEXT LUNGES")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("JUMPING LUNGES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("BURPEE")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("CRUNCHES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()   
    sleep(1)
    printf("UP NEXT LUNGES")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("JUMPING LUNGES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("BURPEE")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("CRUNCHES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("PLANK")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("PUSHups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("Voila That's it for today")
    sleep(1)
    printf("Stay healthy Cheers")
    printf("NEXT PUSH ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT PULL ups")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("NEXT SQUATS")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    sleep(1)
    printf("UP NEXT LUNGES")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("JUMPING LUNGES")
    sleep(1)
    printf("Do for 30 seconds")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("BURPEE")
    sleep(1)
    printf("Do for 30 sec")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("CRUNCHES")
    sleep(1)
    printf("Do for 30 sec")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("PLANK")
    sleep(1)
    printf("Do for 30 sec")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("PUSHups")
    sleep(1)
    printf("Do for 30 sec")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    sleep(1)
    printf("Do for 30 sec")
    printf("START")
    timer_30()
    printf("Take rest")
    timer_10()
    printf("Voila That's it for today")
    sleep(1)
    printf("Stay healthy Cheers")
